def get_hyper_paras():
    BATCH = 64
    STEPS_PER_EPOCH = 800//BATCH
    VALIDATION_STEPS = 200//BATCH
    EPOCHS = 100
    VAL_SUBSPLITS = 5
    return BATCH,STEPS_PER_EPOCH,VALIDATION_STEPS,EPOCHS,VAL_SUBSPLITS